# Generated by Django 4.2.4 on 2023-11-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bias',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('sectors', models.CharField(max_length=45)),
                ('key_words', models.CharField(max_length=45)),
                ('study_level', models.CharField(max_length=45)),
                ('charge', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('bias', models.ManyToManyField(to='Offer.bias')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('corrected_description', models.TextField()),
                ('highlight_words', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offer.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('critical_words', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offer.offer')),
            ],
        ),
    ]
