# Generated by Django 4.2.4 on 2023-10-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bias',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='offer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Offer.offer'),
            preserve_default=False,
        ),
    ]
