# Generated by Django 4.2.4 on 2023-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
