# Generated by Django 4.2.4 on 2023-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_remove_offer_bias_remove_offer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bias',
            field=models.ManyToManyField(to='Offer.bias'),
        ),
    ]
