# Generated by Django 4.2.4 on 2023-11-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
        ('Offer', '0002_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Analytics.company'),
            preserve_default=False,
        ),
    ]
